package com.bracits.epms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedbackTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackTypeAllPropertiesEquals(FeedbackType expected, FeedbackType actual) {
        assertFeedbackTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedbackTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackTypeAllUpdatablePropertiesEquals(FeedbackType expected, FeedbackType actual) {
        assertFeedbackTypeUpdatableFieldsEquals(expected, actual);
        assertFeedbackTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackTypeAutoGeneratedPropertiesEquals(FeedbackType expected, FeedbackType actual) {
        assertThat(expected)
            .as("Verify FeedbackType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackTypeUpdatableFieldsEquals(FeedbackType expected, FeedbackType actual) {
        assertThat(expected)
            .as("Verify FeedbackType relevant properties")
            .satisfies(e -> assertThat(e.getFeedbackname()).as("check feedbackname").isEqualTo(actual.getFeedbackname()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedbackTypeUpdatableRelationshipsEquals(FeedbackType expected, FeedbackType actual) {}
}
