package com.bracits.epms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RatingScaleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingScaleAllPropertiesEquals(RatingScale expected, RatingScale actual) {
        assertRatingScaleAutoGeneratedPropertiesEquals(expected, actual);
        assertRatingScaleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingScaleAllUpdatablePropertiesEquals(RatingScale expected, RatingScale actual) {
        assertRatingScaleUpdatableFieldsEquals(expected, actual);
        assertRatingScaleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingScaleAutoGeneratedPropertiesEquals(RatingScale expected, RatingScale actual) {
        assertThat(expected)
            .as("Verify RatingScale auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingScaleUpdatableFieldsEquals(RatingScale expected, RatingScale actual) {
        assertThat(expected)
            .as("Verify RatingScale relevant properties")
            .satisfies(e -> assertThat(e.getScaletype()).as("check scaletype").isEqualTo(actual.getScaletype()))
            .satisfies(e -> assertThat(e.getRatingscales()).as("check ratingscales").isEqualTo(actual.getRatingscales()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRatingScaleUpdatableRelationshipsEquals(RatingScale expected, RatingScale actual) {}
}
