package com.bracits.epms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SkillDevelopmentTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillDevelopmentTypeAllPropertiesEquals(SkillDevelopmentType expected, SkillDevelopmentType actual) {
        assertSkillDevelopmentTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertSkillDevelopmentTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillDevelopmentTypeAllUpdatablePropertiesEquals(SkillDevelopmentType expected, SkillDevelopmentType actual) {
        assertSkillDevelopmentTypeUpdatableFieldsEquals(expected, actual);
        assertSkillDevelopmentTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillDevelopmentTypeAutoGeneratedPropertiesEquals(SkillDevelopmentType expected, SkillDevelopmentType actual) {
        assertThat(expected)
            .as("Verify SkillDevelopmentType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillDevelopmentTypeUpdatableFieldsEquals(SkillDevelopmentType expected, SkillDevelopmentType actual) {
        assertThat(expected)
            .as("Verify SkillDevelopmentType relevant properties")
            .satisfies(
                e -> assertThat(e.getSkilldevelopmentname()).as("check skilldevelopmentname").isEqualTo(actual.getSkilldevelopmentname())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSkillDevelopmentTypeUpdatableRelationshipsEquals(SkillDevelopmentType expected, SkillDevelopmentType actual) {}
}
